sudo: required
language: python
python:
- 3.6
services:
- docker
before_install:
- git submodule update --init --recursive
script:
-  bash docker_test.sh
notifications:
  webhooks:
    urls:
      - $WEBHOOK
    on_success: always
    on_failure: always
